### ISSUE TITLE
Before v1.0 (Roadmap)

### ISSUE THREAD

**Issue by nelsonpecora** [nymag/clay-kiln#234]
Before v1.0 is released, we should do the following:
- [x] make sure async decorators, behaviors, and validators work
- [x] pull out behaviors from kiln, or make them incredibly standardized (argument names, etc)
- [x] make sure `decorators` api is :100: (performant, stable)
- [x] check code coverage, and update the badge in the readme
- [x] check the docs, and update them to make them more clear
